name: Release on Merge

on:
  pull_request:
    branches:
      - main
    types:
      - closed
jobs:
  Release:
    if: ${{ github.event.pull_request.merged }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          node-version: 18
          registry-url: https://npm.pkg.github.com/
      - name: "install deps"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm i
      - name: "release"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "${{github.actor}}"
          git config user.email "${{github.actor}}@users.noreply.github.com"
          npm run release
          git push --follow-tags origin main
